### ISSUE TITLE
Tokens treated as named nodes

### ISSUE THREAD

**Issue by Gauteab** [Razzeee/tree-sitter-elm#39]
When parsing a simple expression like `x = 5`, all three leaf nodes are marked as "named".
This makes it much more difficult to create an ast because you can differentiate between string tokens and tokens carrying data.

In the grammar (around line 563) there is a section of rules defining tokens:
```
comma: ($) => ",",
eq: ($) => "=",
arrow: ($) => "->",
```

From what i understand reading https://tree-sitter.github.io/tree-sitter/using-parsers#named-vs-anonymous-nodes
these should be used directly as strings and the rest of the grammar.

Is there a reason it is implemented like this, or is it perhaps an oversight?

P.S
Thank you for your work on this project :)

**Comment by Razzeee** [comment]
In this case it's probably done so that you don't need to ask for anonymous nodes when your looking for an "eq" node.
In general, it can probably improved, the original inception of this was basically a re-implementation of the intelliJ elm ast. And most nodes ended up being named due to that.

**Comment by Razzeee** [comment]
I'm not really sure what I want here, it's nice for debugging to have these show up in tests. Then again, they probably don't add much value. I'm going to close this for now, feel free to reopen, if you have concerns/more data.
