### ISSUE TITLE
rust crate

### ISSUE THREAD

**Issue by dullbananas** [Razzeee/tree-sitter-elm#54]
most tree sitter grammars provide a binding in a rust crate

**Comment by harrysarson** [comment]
I am wanting exactly this (for https://github.com/mpizenberg/elm-test-rs/pull/15) and can work on a patch :)

**Comment by Razzeee** [comment]
Can we just copy https://github.com/tree-sitter/tree-sitter-go/tree/master/bindings/rust amend it and create a pipeline to push to crates.io?

**Comment by Razzeee** [comment]
More examples:
https://github.com/tree-sitter/tree-sitter-java
https://github.com/tree-sitter/tree-sitter-javascript
https://github.com/tree-sitter/tree-sitter-python
https://github.com/tree-sitter/tree-sitter-ruby
https://github.com/tree-sitter/tree-sitter-c-sharp

None of these seem to have an automated release

**Comment by dullbananas** [comment]
perfect timing: i was looking at crates.io and it's the newest crate

![image](https://user-images.githubusercontent.com/47706471/99888112-59ec8c80-2c07-11eb-893a-d38a2d2fb581.jpeg)
