### ISSUE TITLE
Tests fail for elm-json-decode-pipeline

### ISSUE THREAD

**Issue by buinauskas** [Razzeee/tree-sitter-elm#9]
Tests fail for [elm-json-decode-pipeline](https://github.com/NoRedInk/elm-json-decode-pipeline) repository. This is the exact code that causes the failure:

```
-----------------------------------------------------------------
examples/elm-json-decode-pipeline/tests/Tests.elm                      1 ms    (ERROR [44, 32] - [44, 33])
-----------------------------------------------------------------
```

Have added to `parse-examples`:
```
checkout_at "examples/elm-json-decode-pipeline" "NoRedInk/elm-json-decode-pipeline" "d9c10a2b388176569fe3e88ef0e2b6fc19d9beeb"
```

**Comment by Razzeee** [comment]
The repo somehow defaults to the old 0.18 version, if you use this sha it works:
`checkout_at "examples/elm-json-decode-pipeline" "NoRedInk/elm-json-decode-pipeline" "ca1e0dcaa0439510bae8be39281e9d2f0c5b33e2"`
